services:
  - type: web
    name: cme-detection-backend
    env: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true

